#!/usr/bin/env bash
# ClawAV Oneshot Installer — Interactive guided install
#
# Usage:
#   curl -sSL https://raw.githubusercontent.com/coltz108/ClawAV/main/scripts/oneshot-install.sh | sudo bash
#   curl -sSL https://raw.githubusercontent.com/coltz108/ClawAV/main/scripts/oneshot-install.sh | sudo bash -s -- --version v0.2.7
#   curl -sSL https://raw.githubusercontent.com/coltz108/ClawAV/main/scripts/oneshot-install.sh | sudo bash -s -- --update
#
set -euo pipefail

REPO="coltz108/ClawAV"
VERSION="latest"
MODE="install"

# Parse arguments
while [[ $# -gt 0 ]]; do
    case "$1" in
        --update)   MODE="update"; shift ;;
        --version)  VERSION="$2"; shift 2 ;;
        -*)         echo "Unknown flag: $1" >&2; exit 1 ;;
        *)          VERSION="$1"; shift ;;
    esac
done

# ═══════════════════════════════════════════════════════════════════════════════
# INSTALL DETECTION
# ═══════════════════════════════════════════════════════════════════════════════
HAS_BINARY=false; [[ -f /usr/local/bin/clawav ]] && HAS_BINARY=true
HAS_CONFIG=false; [[ -f /etc/clawav/config.toml ]] && HAS_CONFIG=true
HAS_KEY=false;    [[ -f /etc/clawav/admin.key.hash ]] && HAS_KEY=true
HAD_ADMIN_KEY="$HAS_KEY"

if [[ "$HAS_BINARY" == true && "$HAS_CONFIG" == true && "$HAS_KEY" == true ]]; then
    EXISTING_INSTALL=true
elif [[ "$HAS_BINARY" == true || "$HAS_CONFIG" == true || "$HAS_KEY" == true ]]; then
    EXISTING_INSTALL=partial
else
    EXISTING_INSTALL=false
fi

# Route --update to interactive detection
if [[ "$MODE" == "update" ]]; then
    if [[ "$EXISTING_INSTALL" == true ]]; then
        MODE="upgrade"
    else
        echo -e "\033[0;31m[ERROR]\033[0m ClawAV not fully installed. Run without --update for fresh install." >&2
        exit 1
    fi
fi

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
CYAN='\033[0;36m'
BOLD='\033[1m'
NC='\033[0m'

log()  { echo -e "${GREEN}[CLAWAV]${NC} $*"; }
warn() { echo -e "${YELLOW}[WARN]${NC} $*"; }
die()  { echo -e "${RED}[ERROR]${NC} $*" >&2; exit 1; }

confirm() {
    local prompt="$1"
    local response
    while true; do
        echo -en "${CYAN}${prompt}${NC} " > /dev/tty
        read -r response < /dev/tty
        case "$response" in
            [yY]|[yY][eE][sS]) return 0 ;;
            [nN]|[nN][oO]) return 1 ;;
            *) echo "Please answer yes or no." > /dev/tty ;;
        esac
    done
}

wait_for_enter() {
    echo -en "${CYAN}$1${NC}" > /dev/tty
    read -r < /dev/tty
}

[[ $EUID -eq 0 ]] || die "Must run as root (pipe to sudo bash, or run with sudo)"

# ═══════════════════════════════════════════════════════════════════════════════
# SUDOERS ALLOWLIST FUNCTION (shared between fresh install and upgrade)
# ═══════════════════════════════════════════════════════════════════════════════
install_sudoers_allowlist() {
    local agent_user="$1"
    [[ -z "$agent_user" ]] && return 0

    log "Installing sudoers allowlist for '$agent_user'..."

    # Remove old deny-list approach if present
    if [[ -f /etc/sudoers.d/clawav-deny ]]; then
        chattr -i /etc/sudoers.d/clawav-deny 2>/dev/null || true
        rm -f /etc/sudoers.d/clawav-deny
        log "Removed old clawav-deny (consolidated into allowlist)"
    fi

    local POLICY_FILE="/etc/sudoers.d/010_pi-nopasswd"
    chattr -i "$POLICY_FILE" 2>/dev/null || true

    cat > "$POLICY_FILE" << POLICYEOF
# ClawAV Sudoers Policy for AI Agent (auto-generated by oneshot-install.sh)
# Allowlist + path-restricted deny rules. Last match wins.
# This file is immutable (chattr +i) — requires admin to modify.

# ── ALLOW RULES (base grants) ──

# Read-only tools
$agent_user ALL=(ALL) NOPASSWD: /usr/bin/cat, /usr/bin/ls, /usr/bin/head, \\
    /usr/bin/tail, /usr/bin/grep, /usr/bin/find, /usr/bin/stat, \\
    /usr/bin/wc, /usr/bin/diff, /usr/bin/file, /usr/bin/readlink, \\
    /usr/bin/getent, /usr/bin/id, /usr/bin/whoami, /usr/bin/test, \\
    /usr/bin/sort, /usr/bin/uniq, /usr/bin/tr, /usr/bin/cut, \\
    /usr/bin/md5sum, /usr/bin/sha256sum, /usr/bin/strings

# Log & diagnostics
$agent_user ALL=(ALL) NOPASSWD: /usr/bin/journalctl, /usr/bin/dmesg, \\
    /usr/bin/ss, /usr/bin/lsof, /usr/sbin/lsof, \\
    /usr/bin/df, /usr/bin/du, /usr/bin/mount, \\
    /usr/bin/free, /usr/bin/uptime, /usr/bin/top, /usr/bin/ps, \\
    /usr/bin/ip, /usr/sbin/ip, /usr/bin/netstat, /usr/sbin/netstat

# Service management (start/restart only — stop/disable/mask denied below)
$agent_user ALL=(ALL) NOPASSWD: /usr/bin/systemctl status *, \\
    /usr/bin/systemctl is-active *, \\
    /usr/bin/systemctl show *, \\
    /usr/bin/systemctl list-units *, \\
    /usr/bin/systemctl start *, \\
    /usr/bin/systemctl restart *, \\
    /usr/bin/systemctl enable *, \\
    /usr/bin/systemctl daemon-reload, \\
    /usr/bin/systemd-run *

# Package management
$agent_user ALL=(ALL) NOPASSWD: /usr/bin/apt, /usr/bin/apt-get, \\
    /usr/bin/dpkg, /usr/bin/apt-cache

# Write tools (restricted by deny rules below)
$agent_user ALL=(ALL) NOPASSWD: /usr/bin/tee, /usr/bin/tee -a *, \\
    /usr/bin/cp, /usr/bin/mv, /usr/bin/ln, \\
    /usr/bin/mkdir, /usr/bin/chmod, /usr/bin/chown, \\
    /usr/bin/rm, /usr/bin/rmdir, /usr/bin/touch, /usr/bin/install

# Text processing & network (non-destructive use)
$agent_user ALL=(ALL) NOPASSWD: /usr/bin/sed, /usr/bin/awk, \\
    /usr/bin/curl, /usr/bin/wget

# ── DENY RULES (last match wins — override allows above) ──

# Shells & interpreters (root shell equivalent)
$agent_user ALL=(ALL) !/usr/bin/bash, !/usr/bin/sh, !/usr/bin/dash, \\
    !/usr/bin/zsh, !/usr/bin/fish, \\
    !/usr/bin/python3, !/usr/bin/python3 *, \\
    !/usr/bin/python, !/usr/bin/python *, \\
    !/usr/bin/perl, !/usr/bin/perl *, \\
    !/usr/bin/ruby, !/usr/bin/ruby *, \\
    !/usr/bin/node, !/usr/bin/node *, \\
    !/usr/local/bin/node, !/usr/local/bin/node *, \\
    !/usr/bin/env bash, !/usr/bin/env sh, \\
    !/usr/bin/env python3, !/usr/bin/env perl, \\
    !/usr/bin/env node

# su / sudo escalation
$agent_user ALL=(ALL) !/usr/bin/su, !/usr/bin/su *, \\
    !/usr/sbin/su, !/usr/sbin/su *

# User/password management
$agent_user ALL=(ALL) !/usr/bin/passwd, !/usr/bin/passwd *, \\
    !/usr/bin/chpasswd, \\
    !/usr/sbin/useradd, !/usr/sbin/usermod, !/usr/sbin/usermod *, \\
    !/usr/sbin/userdel, !/usr/sbin/groupmod, \\
    !/usr/sbin/deluser, !/usr/sbin/adduser, \\
    !/usr/bin/chage, !/usr/bin/gpasswd, \\
    !/usr/bin/chsh, !/usr/bin/chfn

# Sudoers editing
$agent_user ALL=(ALL) !/usr/sbin/visudo, !/usr/bin/sudoedit

# Process killing
$agent_user ALL=(ALL) !/usr/bin/kill, !/usr/bin/kill *, \\
    !/usr/bin/killall, !/usr/bin/killall *, \\
    !/usr/bin/pkill, !/usr/bin/pkill *

# systemctl destructive ops
$agent_user ALL=(ALL) !/usr/bin/systemctl stop *, \\
    !/usr/bin/systemctl disable *, \\
    !/usr/bin/systemctl mask *

# chattr (prevent immutability manipulation)
$agent_user ALL=(ALL) !/usr/bin/chattr, !/usr/bin/chattr *

# In-place file editing & raw writes
$agent_user ALL=(ALL) !/usr/bin/sed -i *, !/usr/bin/sed --in-place *
$agent_user ALL=(ALL) !/usr/bin/dd, !/usr/bin/dd *

# Write tools targeting auth files (/etc/shadow, passwd, group, gshadow)
$agent_user ALL=(ALL) !/usr/bin/tee /etc/shadow, !/usr/bin/tee -a /etc/shadow, \\
    !/usr/bin/tee /etc/passwd, !/usr/bin/tee -a /etc/passwd, \\
    !/usr/bin/tee /etc/group, !/usr/bin/tee -a /etc/group, \\
    !/usr/bin/tee /etc/gshadow, !/usr/bin/tee -a /etc/gshadow, \\
    !/usr/bin/cp * /etc/shadow, !/usr/bin/cp * /etc/passwd, \\
    !/usr/bin/cp * /etc/group, !/usr/bin/cp * /etc/gshadow, \\
    !/usr/bin/mv * /etc/shadow, !/usr/bin/mv * /etc/passwd, \\
    !/usr/bin/mv * /etc/group, !/usr/bin/mv * /etc/gshadow, \\
    !/usr/bin/chmod * /etc/shadow, !/usr/bin/chmod * /etc/passwd, \\
    !/usr/bin/chown * /etc/shadow, !/usr/bin/chown * /etc/passwd, \\
    !/usr/bin/rm /etc/shadow, !/usr/bin/rm /etc/passwd

# Write tools targeting sudoers
$agent_user ALL=(ALL) !/usr/bin/tee /etc/sudoers, !/usr/bin/tee -a /etc/sudoers, \\
    !/usr/bin/tee /etc/sudoers.d/*, !/usr/bin/tee -a /etc/sudoers.d/*, \\
    !/usr/bin/cp * /etc/sudoers, !/usr/bin/cp * /etc/sudoers.d/*, \\
    !/usr/bin/mv * /etc/sudoers, !/usr/bin/mv * /etc/sudoers.d/*, \\
    !/usr/bin/chmod * /etc/sudoers, !/usr/bin/chmod * /etc/sudoers.d/*, \\
    !/usr/bin/chown * /etc/sudoers, !/usr/bin/chown * /etc/sudoers.d/*, \\
    !/usr/bin/rm /etc/sudoers, !/usr/bin/rm /etc/sudoers.d/*, \\
    !/usr/bin/rm -f /etc/sudoers.d/*, !/usr/bin/rm -rf /etc/sudoers.d

# Write tools targeting SSH
$agent_user ALL=(ALL) !/usr/bin/tee /etc/ssh/*, !/usr/bin/tee -a /etc/ssh/*, \\
    !/usr/bin/cp * /etc/ssh/*, !/usr/bin/mv * /etc/ssh/*, \\
    !/usr/bin/tee /root/.ssh/*, !/usr/bin/tee -a /root/.ssh/*, \\
    !/usr/bin/cp * /root/.ssh/*, !/usr/bin/mkdir /root/.ssh, \\
    !/usr/bin/chmod * /etc/ssh/*, !/usr/bin/chown * /etc/ssh/*

# Write tools targeting PAM
$agent_user ALL=(ALL) !/usr/bin/tee /etc/pam.d/*, !/usr/bin/tee -a /etc/pam.d/*, \\
    !/usr/bin/cp * /etc/pam.d/*, !/usr/bin/mv * /etc/pam.d/*, \\
    !/usr/bin/rm /etc/pam.d/*, !/usr/bin/rm -f /etc/pam.d/*

# Write tools targeting ClawAV
$agent_user ALL=(ALL) !/usr/bin/tee /usr/local/bin/clawav, \\
    !/usr/bin/tee /etc/clawav/*, !/usr/bin/tee -a /etc/clawav/*, \\
    !/usr/bin/cp * /usr/local/bin/clawav, !/usr/bin/cp * /etc/clawav/*, \\
    !/usr/bin/mv * /usr/local/bin/clawav, !/usr/bin/mv * /etc/clawav/*, \\
    !/usr/bin/chmod * /usr/local/bin/clawav, !/usr/bin/chmod * /etc/clawav/*, \\
    !/usr/bin/chown * /usr/local/bin/clawav, !/usr/bin/chown * /etc/clawav/*, \\
    !/usr/bin/rm /usr/local/bin/clawav, !/usr/bin/rm -f /usr/local/bin/clawav, \\
    !/usr/bin/rm -rf /etc/clawav, !/usr/bin/rm -rf /etc/clawav/*, \\
    !/usr/bin/tee /etc/systemd/system/clawav.service, \\
    !/usr/bin/cp * /etc/systemd/system/clawav.service, \\
    !/usr/bin/mv * /etc/systemd/system/clawav.service, \\
    !/usr/bin/rm /etc/systemd/system/clawav.service

# Write tools targeting ld.so (library injection)
$agent_user ALL=(ALL) !/usr/bin/tee /etc/ld.so.preload, !/usr/bin/tee -a /etc/ld.so.preload, \\
    !/usr/bin/cp * /etc/ld.so.preload, \\
    !/usr/bin/tee /etc/ld.so.conf, !/usr/bin/tee -a /etc/ld.so.conf, \\
    !/usr/bin/cp * /etc/ld.so.conf

# Write tools targeting cron (persistence)
$agent_user ALL=(ALL) !/usr/bin/tee /etc/cron.d/*, !/usr/bin/tee -a /etc/cron.d/*, \\
    !/usr/bin/cp * /etc/cron.d/*, \\
    !/usr/bin/tee /var/spool/cron/crontabs/root, \\
    !/usr/bin/tee -a /var/spool/cron/crontabs/root, \\
    !/usr/bin/rm /etc/cron.d/*, !/usr/bin/rm -f /etc/cron.d/*
POLICYEOF

    chmod 440 "$POLICY_FILE"
    if visudo -cf "$POLICY_FILE"; then
        chattr +i "$POLICY_FILE"
        log "✓ Agent account locked down with allowlist policy"
    else
        echo "$agent_user ALL=(ALL) NOPASSWD: ALL" > "$POLICY_FILE"
        chmod 440 "$POLICY_FILE"
        warn "Sudoers allowlist had syntax errors — fell back to NOPASSWD:ALL. Agent not locked down!"
    fi
}

# ═══════════════════════════════════════════════════════════════════════════════
# INTERACTIVE INSTALL DETECTION MENU
# ═══════════════════════════════════════════════════════════════════════════════
if [[ "$EXISTING_INSTALL" == "true" && "$MODE" == "install" ]]; then
    echo ""
    echo -e "${CYAN}${BOLD}═══════════════════════════════════════════════════════════════${NC}"
    echo -e "${CYAN}${BOLD}  🛡️  ClawAV is already installed                               ${NC}"
    echo -e "${CYAN}${BOLD}═══════════════════════════════════════════════════════════════${NC}"
    echo ""
    CURRENT_VERSION=$(/usr/local/bin/clawav --version 2>/dev/null || echo "unknown")
    echo -e "  Current version: ${BOLD}$CURRENT_VERSION${NC}"
    echo ""
    echo -e "  ${BOLD}1)${NC} Upgrade        — swap binaries + refresh patterns & policy, keep config & key"
    echo -e "  ${BOLD}2)${NC} Reconfigure    — re-run config wizard, keep key"
    echo -e "  ${BOLD}3)${NC} Full reinstall — nuke everything, start from scratch"
    echo -e "  ${BOLD}4)${NC} Abort"
    echo ""
    echo -en "  ${CYAN}Choose [1-4]: ${NC}" > /dev/tty
    read -r menu_choice < /dev/tty
    case "$menu_choice" in
        1) MODE="upgrade" ;;
        2) MODE="install" ;;  # Continue to full flow (reconfigure)
        3) MODE="install"; HAD_ADMIN_KEY=false ;;  # Full reinstall — treat as fresh
        4) echo "Aborted."; exit 0 ;;
        *) die "Invalid choice" ;;
    esac
elif [[ "$EXISTING_INSTALL" == "partial" && "$MODE" == "install" ]]; then
    echo ""
    warn "Partial ClawAV installation detected (some files missing)."
    echo -e "  Binary:     $([ "$HAS_BINARY" = true ] && echo "✓" || echo "✗")"
    echo -e "  Config:     $([ "$HAS_CONFIG" = true ] && echo "✓" || echo "✗")"
    echo -e "  Admin key:  $([ "$HAS_KEY" = true ] && echo "✓" || echo "✗")"
    echo ""
    if confirm "Proceed with fresh install? (will overwrite existing files) [y/n]"; then
        HAD_ADMIN_KEY=false
    else
        echo "Aborted."
        exit 0
    fi
fi

# ═══════════════════════════════════════════════════════════════════════════════
# UPGRADE MODE
# ═══════════════════════════════════════════════════════════════════════════════
if [[ "$MODE" == "upgrade" ]]; then
    echo ""
    echo -e "${CYAN}${BOLD}═══════════════════════════════════════════════════════════════${NC}"
    echo -e "${CYAN}${BOLD}  🔄  ClawAV Upgrade                                           ${NC}"
    echo -e "${CYAN}${BOLD}═══════════════════════════════════════════════════════════════${NC}"
    echo ""

    CURRENT_VERSION=$(/usr/local/bin/clawav --version 2>/dev/null || echo "unknown")

    # Detect architecture
    ARCH=$(uname -m)
    case "$ARCH" in
        x86_64|amd64)   ARCH_LABEL="x86_64" ;;
        aarch64|arm64)   ARCH_LABEL="aarch64" ;;
        *)               die "Unsupported architecture: $ARCH" ;;
    esac

    # Resolve version
    if [[ "$VERSION" == "latest" ]]; then
        log "Fetching latest release..."
        VERSION=$(curl -sSL "https://api.github.com/repos/$REPO/releases/latest" | grep '"tag_name"' | sed -E 's/.*"([^"]+)".*/\1/')
        [[ -n "$VERSION" ]] || die "Could not determine latest version"
    fi

    echo -e "  Current version: ${BOLD}$CURRENT_VERSION${NC}"
    echo -e "  Available:       ${BOLD}$VERSION${NC}"
    echo ""

    if ! confirm "Upgrade to $VERSION? [Y/n]"; then
        echo "Aborted."
        exit 0
    fi

    # Download new binaries to temp
    TMPDIR=$(mktemp -d)
    trap 'rm -rf "$TMPDIR"' EXIT

    BASE_URL="https://github.com/$REPO/releases/download/$VERSION"
    log "Downloading clawav..."
    curl -sSL -f -o "$TMPDIR/clawav" "$BASE_URL/clawav-${ARCH_LABEL}-linux" || die "Download failed: $BASE_URL/clawav-${ARCH_LABEL}-linux"
    log "Downloading clawsudo..."
    curl -sSL -f -o "$TMPDIR/clawsudo" "$BASE_URL/clawsudo-${ARCH_LABEL}-linux" || die "Download failed"
    chmod +x "$TMPDIR/clawav" "$TMPDIR/clawsudo"

    # Download updated policies
    log "Downloading updated policies..."
    mkdir -p "$TMPDIR/policies"
    curl -sSL -f -o "$TMPDIR/policies/default.yaml" "https://raw.githubusercontent.com/$REPO/$VERSION/policies/default.yaml" 2>/dev/null || true

    # Download updated SecureClaw patterns
    log "Downloading SecureClaw patterns..."
    SECURECLAW_BASE="https://raw.githubusercontent.com/adversa-ai/secureclaw/main/secureclaw/skill/configs"
    mkdir -p "$TMPDIR/secureclaw"
    for pattern in injection-patterns.json dangerous-commands.json privacy-rules.json supply-chain-ioc.json; do
        curl -sSL -f -o "$TMPDIR/secureclaw/$pattern" "$SECURECLAW_BASE/$pattern" 2>/dev/null && \
            log "  ✓ $pattern" || warn "  ✗ $pattern (non-fatal)"
    done

    # Stop service
    log "Stopping ClawAV service..."
    systemctl stop clawav 2>/dev/null || true
    sleep 1

    # Remove immutable flags
    log "Removing immutable flags..."
    chattr -i /usr/local/bin/clawav 2>/dev/null || true
    chattr -i /usr/local/bin/clawsudo 2>/dev/null || true
    chattr -i /usr/local/bin/clawav-tray 2>/dev/null || true
    chattr -i /etc/clawav/admin.key.hash 2>/dev/null || true
    chattr -i /etc/sudoers.d/010_pi-nopasswd 2>/dev/null || true

    # Replace binaries
    log "Installing new binaries..."
    cp "$TMPDIR/clawav" /usr/local/bin/clawav
    cp "$TMPDIR/clawsudo" /usr/local/bin/clawsudo
    chmod 755 /usr/local/bin/clawav /usr/local/bin/clawsudo

    # Update tray binary if it exists in the release and is installed locally
    TRAY_ARTIFACT="clawav-tray-${ARCH_LABEL}-linux"
    if [[ -f /usr/local/bin/clawav-tray ]]; then
        log "Updating tray binary..."
        if curl -sSL -f -o "$TMPDIR/clawav-tray" "$BASE_URL/$TRAY_ARTIFACT" 2>/dev/null; then
            chmod +x "$TMPDIR/clawav-tray"
            cp "$TMPDIR/clawav-tray" /usr/local/bin/clawav-tray
            chmod 755 /usr/local/bin/clawav-tray
            log "✓ Tray binary updated"
        else
            warn "Tray binary not available in this release — keeping existing"
        fi
    fi

    # Update SecureClaw patterns (always overwrite — these are upstream)
    for f in "$TMPDIR"/secureclaw/*.json; do
        [[ -f "$f" ]] && cp "$f" "/etc/clawav/secureclaw/"
    done

    # Update default policy
    if [[ -f "$TMPDIR/policies/default.yaml" ]]; then
        cp "$TMPDIR/policies/default.yaml" "/etc/clawav/policies/default.yaml"
        log "Updated default policy"
    fi

    # Regenerate sudoers allowlist from latest template
    AGENT_USERNAME=$(grep -oP 'watched_user = "\K[^"]+' /etc/clawav/config.toml 2>/dev/null || echo "")
    # If watched_user is a UID, resolve to username
    if [[ "$AGENT_USERNAME" =~ ^[0-9]+$ ]]; then
        AGENT_USERNAME=$(getent passwd "$AGENT_USERNAME" | cut -d: -f1 || echo "")
    fi
    if [[ -n "$AGENT_USERNAME" ]]; then
        install_sudoers_allowlist "$AGENT_USERNAME"
    fi

    # Re-set immutable flags
    log "Re-setting immutable flags..."
    chattr +i /usr/local/bin/clawav
    chattr +i /usr/local/bin/clawsudo
    [[ -f /usr/local/bin/clawav-tray ]] && chattr +i /usr/local/bin/clawav-tray
    [[ -f /etc/clawav/admin.key.hash ]] && chattr +i /etc/clawav/admin.key.hash

    # Restart service
    log "Starting ClawAV..."
    systemctl start clawav
    sleep 2

    if systemctl is-active --quiet clawav; then
        NEW_VERSION=$(/usr/local/bin/clawav --version 2>/dev/null || echo "$VERSION")
        echo ""
        echo -e "${GREEN}${BOLD}═══════════════════════════════════════════════════════════════${NC}"
        echo -e "${GREEN}${BOLD}  ✅  ClawAV upgraded: $CURRENT_VERSION → $NEW_VERSION         ${NC}"
        echo -e "${GREEN}${BOLD}═══════════════════════════════════════════════════════════════${NC}"
        echo ""
        echo -e "  ${GREEN}✓ Your existing admin key and config are unchanged.${NC}"
        echo ""
        echo -e "  ${BOLD}Status:${NC}  systemctl status clawav"
        echo -e "  ${BOLD}Logs:${NC}    journalctl -u clawav -f"
        echo ""
    else
        die "ClawAV failed to start after upgrade — check: journalctl -u clawav -n 50"
    fi

    exit 0
fi

# ═══════════════════════════════════════════════════════════════════════════════
# PHASE 1: DOWNLOAD
# ═══════════════════════════════════════════════════════════════════════════════
echo ""
echo -e "${GREEN}${BOLD}═══════════════════════════════════════════════════════════════${NC}"
echo -e "${GREEN}${BOLD}  🛡️  ClawAV Installer                                        ${NC}"
echo -e "${GREEN}${BOLD}═══════════════════════════════════════════════════════════════${NC}"
echo ""
echo -e "  This installer will:"
echo -e "  ${BOLD}1.${NC} Download ClawAV binaries + SecureClaw patterns"
echo -e "  ${BOLD}2.${NC} Let you configure before anything is locked down"
echo -e "  ${BOLD}3.${NC} Lock the installation (immutable — requires recovery to undo)"
echo ""

if ! confirm "Continue? [y/n]"; then
    echo "Aborted."
    exit 0
fi

# ── Detect architecture ──────────────────────────────────────────────────────
ARCH=$(uname -m)
case "$ARCH" in
    x86_64|amd64)   ARCH_LABEL="x86_64" ;;
    aarch64|arm64)   ARCH_LABEL="aarch64" ;;
    *)               die "Unsupported architecture: $ARCH (need x86_64 or aarch64)" ;;
esac
log "Detected architecture: $ARCH_LABEL"

# ── Resolve version ──────────────────────────────────────────────────────────
if [[ "$VERSION" == "latest" ]]; then
    log "Fetching latest release..."
    VERSION=$(curl -sSL "https://api.github.com/repos/$REPO/releases/latest" | grep '"tag_name"' | sed -E 's/.*"([^"]+)".*/\1/')
    [[ -n "$VERSION" ]] || die "Could not determine latest version. Check https://github.com/$REPO/releases"
fi
log "Installing ClawAV $VERSION"

# ── Download binaries ────────────────────────────────────────────────────────
TMPDIR=$(mktemp -d)
trap 'rm -rf "$TMPDIR"' EXIT

BASE_URL="https://github.com/$REPO/releases/download/$VERSION"
CLAWAV_ARTIFACT="clawav-${ARCH_LABEL}-linux"
CLAWSUDO_ARTIFACT="clawsudo-${ARCH_LABEL}-linux"

log "Downloading $CLAWAV_ARTIFACT..."
curl -sSL -f -o "$TMPDIR/clawav" "$BASE_URL/$CLAWAV_ARTIFACT" || die "Failed to download clawav binary. Does $VERSION exist? Check: $BASE_URL/$CLAWAV_ARTIFACT"

log "Downloading $CLAWSUDO_ARTIFACT..."
curl -sSL -f -o "$TMPDIR/clawsudo" "$BASE_URL/$CLAWSUDO_ARTIFACT" || die "Failed to download clawsudo binary. Check: $BASE_URL/$CLAWSUDO_ARTIFACT"

chmod +x "$TMPDIR/clawav" "$TMPDIR/clawsudo"

# ── Download config + policies ───────────────────────────────────────────────
log "Downloading default config and policies..."
curl -sSL -f -o "$TMPDIR/config.toml" "https://raw.githubusercontent.com/$REPO/$VERSION/config.toml" || warn "Could not download config.toml"
mkdir -p "$TMPDIR/policies"
curl -sSL -f -o "$TMPDIR/policies/default.yaml" "https://raw.githubusercontent.com/$REPO/$VERSION/policies/default.yaml" 2>/dev/null || true
curl -sSL -f -o "$TMPDIR/policies/clawsudo.yaml" "https://raw.githubusercontent.com/$REPO/$VERSION/policies/clawsudo.yaml" 2>/dev/null || true

# ── Download SecureClaw patterns ──────────────────────────────────────────────
log "Downloading SecureClaw pattern databases..."
SECURECLAW_BASE="https://raw.githubusercontent.com/adversa-ai/secureclaw/main/secureclaw/skill/configs"
mkdir -p "$TMPDIR/secureclaw"
for pattern in injection-patterns.json dangerous-commands.json privacy-rules.json supply-chain-ioc.json; do
    curl -sSL -f -o "$TMPDIR/secureclaw/$pattern" "$SECURECLAW_BASE/$pattern" 2>/dev/null && \
        log "  ✓ $pattern" || \
        warn "  ✗ $pattern (non-fatal)"
done

# ── Install dependencies ──────────────────────────────────────────────────────
if command -v apt-get &>/dev/null; then
    PKG_MGR="apt"
elif command -v dnf &>/dev/null; then
    PKG_MGR="dnf"
elif command -v pacman &>/dev/null; then
    PKG_MGR="pacman"
else
    PKG_MGR=""
fi

if ! command -v auditctl &>/dev/null; then
    log "Installing auditd..."
    case "$PKG_MGR" in
        apt)    apt-get update -qq && apt-get install -y -qq auditd ;;
        dnf)    dnf install -y -q audit ;;
        pacman) pacman -S --noconfirm audit ;;
        *)      warn "Could not install auditd — install it manually" ;;
    esac
fi

if ! command -v apparmor_parser &>/dev/null; then
    log "Installing AppArmor..."
    case "$PKG_MGR" in
        apt)    apt-get install -y -qq apparmor apparmor-utils ;;
        dnf)    dnf install -y -q apparmor apparmor-utils ;;
        pacman) pacman -S --noconfirm apparmor ;;
        *)      warn "Could not install AppArmor — install it manually" ;;
    esac
fi

# ── Create directories and install files (NOT locked down yet) ────────────────
log "Setting up directories..."
mkdir -p /etc/clawav/policies /etc/clawav/secureclaw /var/log/clawav /var/run/clawav

# Stop existing service if upgrading
if systemctl is-active --quiet clawav 2>/dev/null; then
    log "Stopping existing ClawAV service..."
    systemctl stop clawav
    sleep 1
fi

# Remove immutable flags if upgrading
chattr -i /usr/local/bin/clawav 2>/dev/null || true
chattr -i /usr/local/bin/clawsudo 2>/dev/null || true
chattr -i /etc/clawav/config.toml 2>/dev/null || true

log "Installing binaries to /usr/local/bin/..."
cp "$TMPDIR/clawav" /usr/local/bin/clawav
cp "$TMPDIR/clawsudo" /usr/local/bin/clawsudo
chmod 755 /usr/local/bin/clawav /usr/local/bin/clawsudo

# ── Detect display server and install tray binary ─────────────────────────────
DISPLAY_SERVER="headless"
CALLING_USER="${SUDO_USER:-$(whoami)}"
CALLING_HOME=$(eval echo "~$CALLING_USER")

# Check for Wayland
if [[ -n "${WAYLAND_DISPLAY:-}" ]]; then
    DISPLAY_SERVER="wayland"
elif su -s /bin/sh "$CALLING_USER" -c 'echo $WAYLAND_DISPLAY' 2>/dev/null | grep -q .; then
    DISPLAY_SERVER="wayland"
elif loginctl show-session "$(loginctl list-sessions --no-legend 2>/dev/null | grep "$CALLING_USER" | awk '{print $1}' | head -1)" -p Type 2>/dev/null | grep -qi wayland; then
    DISPLAY_SERVER="wayland"
# Check for X11
elif [[ -n "${DISPLAY:-}" ]]; then
    DISPLAY_SERVER="x11"
elif su -s /bin/sh "$CALLING_USER" -c 'echo $DISPLAY' 2>/dev/null | grep -q .; then
    DISPLAY_SERVER="x11"
fi

log "Detected display server: $DISPLAY_SERVER"

if [[ "$DISPLAY_SERVER" != "headless" ]]; then
    TRAY_ARTIFACT="clawav-tray-${ARCH_LABEL}-linux"
    log "Downloading tray binary ($DISPLAY_SERVER detected)..."
    if curl -sSL -f -o "$TMPDIR/clawav-tray" "$BASE_URL/$TRAY_ARTIFACT" 2>/dev/null; then
        chmod +x "$TMPDIR/clawav-tray"
        chattr -i /usr/local/bin/clawav-tray 2>/dev/null || true
        cp "$TMPDIR/clawav-tray" /usr/local/bin/clawav-tray
        chmod 755 /usr/local/bin/clawav-tray
        log "✓ Tray binary installed"

        # Create autostart desktop entry
        AUTOSTART_DIR="$CALLING_HOME/.config/autostart"
        mkdir -p "$AUTOSTART_DIR"
        cat > "$AUTOSTART_DIR/clawav-tray.desktop" <<TRAYEOF
[Desktop Entry]
Type=Application
Name=ClawAV Tray
Exec=/usr/local/bin/clawav-tray
Icon=security-high
Comment=ClawAV security watchdog tray icon
X-GNOME-Autostart-enabled=true
TRAYEOF
        chown "$CALLING_USER:$(id -gn "$CALLING_USER")" "$AUTOSTART_DIR/clawav-tray.desktop"
        log "✓ Tray autostart entry created"

        if [[ "$DISPLAY_SERVER" == "x11" ]]; then
            warn "X11 detected — tray uses D-Bus StatusNotifierItem. You may need snixembed or similar SNI bridge."
        fi
    else
        warn "Tray binary not available in this release — skipping (non-fatal)"
    fi
else
    log "Headless system — skipping tray binary"
fi

# Install config (don't overwrite existing)
if [[ ! -f /etc/clawav/config.toml ]]; then
    [[ -f "$TMPDIR/config.toml" ]] && cp "$TMPDIR/config.toml" /etc/clawav/config.toml
fi

# Install policies (don't overwrite existing)
for f in "$TMPDIR"/policies/*.yaml; do
    fname=$(basename "$f")
    [[ -f "/etc/clawav/policies/$fname" ]] || cp "$f" "/etc/clawav/policies/$fname"
done

# Install SecureClaw patterns
for f in "$TMPDIR"/secureclaw/*.json; do
    [[ -f "$f" ]] && cp "$f" "/etc/clawav/secureclaw/"
done

# Install systemd service
cat > /etc/systemd/system/clawav.service <<'EOF'
[Unit]
Description=ClawAV Security Watchdog
After=network.target auditd.service
Wants=auditd.service

[Service]
Type=simple
ExecStart=/usr/local/bin/clawav --headless --config /etc/clawav/config.toml
Restart=always
RestartSec=5
StandardOutput=journal
StandardError=journal

[Install]
WantedBy=multi-user.target
EOF
systemctl daemon-reload
systemctl enable clawav

echo ""
log "✓ Phase 1 complete — files installed (NOT locked down yet)"

# ═══════════════════════════════════════════════════════════════════════════════
# PHASE 2: CONFIGURE
# ═══════════════════════════════════════════════════════════════════════════════
echo ""
echo -e "${YELLOW}${BOLD}═══════════════════════════════════════════════════════════════${NC}"
echo -e "${YELLOW}${BOLD}  ⚙️   CONFIGURATION                                           ${NC}"
echo -e "${YELLOW}${BOLD}═══════════════════════════════════════════════════════════════${NC}"
echo ""
CONF="/etc/clawav/config.toml"

# ── Watched User ──────────────────────────────────────────────────────────────
CALLING_USER="${SUDO_USER:-$(whoami)}"
CALLING_UID=$(id -u "$CALLING_USER" 2>/dev/null || echo "1000")
echo ""
echo -e "  ${BOLD}User to monitor:${NC} $CALLING_USER (UID $CALLING_UID)"
echo -en "  ${CYAN}Monitor this user? [Y/n] or enter a different UID: ${NC}" > /dev/tty
read -r user_input < /dev/tty
if [[ -z "$user_input" || "$user_input" =~ ^[yY] ]]; then
    WATCH_UID="$CALLING_UID"
else
    WATCH_UID="$user_input"
fi
sed -i "s/^watched_user = .*/watched_user = \"$WATCH_UID\"/" "$CONF"
log "Watching UID: $WATCH_UID"

# ── Additional Users ──────────────────────────────────────────────────────────
echo ""
echo -en "  ${CYAN}Monitor additional UIDs? (comma-separated, or ENTER to skip): ${NC}" > /dev/tty
read -r extra_uids < /dev/tty
if [[ -n "$extra_uids" ]]; then
    # Build TOML array like ["1000", "1001"]
    UIDS_TOML="[\"$WATCH_UID\""
    IFS=',' read -ra EXTRA <<< "$extra_uids"
    for uid in "${EXTRA[@]}"; do
        uid=$(echo "$uid" | tr -d ' ')
        [[ -n "$uid" ]] && UIDS_TOML+=", \"$uid\""
    done
    UIDS_TOML+="]"
    sed -i "s/^.*watched_users = .*/watched_users = $UIDS_TOML/" "$CONF"
    log "Watching UIDs: $UIDS_TOML"
fi

# ── Slack (Optional) ─────────────────────────────────────────────────────────
echo ""
echo -e "  ${BOLD}Slack Alerts${NC} (optional)"
echo -e "  ClawAV can send alerts to an independent Slack webhook."
echo -en "  ${CYAN}Slack webhook URL (or ENTER to skip): ${NC}" > /dev/tty
read -r slack_url < /dev/tty
if [[ -n "$slack_url" ]]; then
    sed -i "s|^webhook_url = .*|webhook_url = \"$slack_url\"|" "$CONF"
    sed -i "s/^enabled = false/enabled = true/" "$CONF"  # enable slack section
    log "Slack alerts enabled"

    echo -en "  ${CYAN}Slack channel (default: #devops): ${NC}" > /dev/tty
    read -r slack_chan < /dev/tty
    [[ -n "$slack_chan" ]] && sed -i "s|^channel = .*|channel = \"$slack_chan\"|" "$CONF"

    echo -en "  ${CYAN}Backup webhook URL (or ENTER to skip): ${NC}" > /dev/tty
    read -r slack_backup < /dev/tty
    [[ -n "$slack_backup" ]] && sed -i "s|^backup_webhook_url = .*|backup_webhook_url = \"$slack_backup\"|" "$CONF"
else
    log "Slack alerts skipped — alerts go to logs only"
fi

# ── API ───────────────────────────────────────────────────────────────────────
echo ""
echo -e "  ${BOLD}JSON API${NC} (LAN-only status/alerts endpoint)"
echo -en "  ${CYAN}Enable API on port 18791? [Y/n]: ${NC}" > /dev/tty
read -r api_input < /dev/tty
if [[ "$api_input" =~ ^[nN] ]]; then
    sed -i '/^\[api\]/,/^$/s/^enabled = true/enabled = false/' "$CONF"
    log "API disabled"
else
    log "API enabled on port 18791"
fi

# ── SecureClaw ────────────────────────────────────────────────────────────────
echo ""
echo -e "  ${BOLD}SecureClaw${NC} (prompt injection + supply chain detection patterns)"
echo -en "  ${CYAN}Enable SecureClaw? [Y/n]: ${NC}" > /dev/tty
read -r sc_input < /dev/tty
if [[ "$sc_input" =~ ^[nN] ]]; then
    log "SecureClaw disabled"
else
    sed -i '/^\[secureclaw\]/,/^$/s/^enabled = false/enabled = true/' "$CONF"
    sed -i "s|^vendor_dir = .*|vendor_dir = \"/etc/clawav/secureclaw\"|" "$CONF"
    log "SecureClaw enabled"
fi

# ── Summary ───────────────────────────────────────────────────────────────────
echo ""
echo -e "  ${GREEN}${BOLD}Configuration summary:${NC}"
echo -e "  ${BOLD}Config file:${NC}    $CONF"
echo -e "  ${BOLD}Watched user:${NC}   UID $WATCH_UID"
if grep -q 'webhook_url = ""' "$CONF" 2>/dev/null || ! grep -q 'webhook_url' "$CONF" 2>/dev/null; then
    echo -e "  ${BOLD}Slack:${NC}          Disabled (logs only)"
else
    echo -e "  ${BOLD}Slack:${NC}          Enabled"
fi
echo ""
echo -e "  ${YELLOW}You can always edit $CONF later (before locking down).${NC}"
echo ""

if ! confirm "Configuration done? Ready to lock down? [y/n]"; then
    echo ""
    echo "  Config saved at /etc/clawav/config.toml"
    echo "  Binaries installed but NOT locked down."
    echo "  Re-run installer when ready to lock down."
    exit 0
fi

# ═══════════════════════════════════════════════════════════════════════════════
# PHASE 3: LOCK DOWN (SWALLOWED KEY)
# ═══════════════════════════════════════════════════════════════════════════════
echo ""
echo -e "${RED}${BOLD}═══════════════════════════════════════════════════════════════${NC}"
echo -e "${RED}${BOLD}  🔒  LOCKING DOWN — THIS IS IRREVERSIBLE WITHOUT RECOVERY     ${NC}"
echo -e "${RED}${BOLD}═══════════════════════════════════════════════════════════════${NC}"
echo ""

# ── Create human admin account ────────────────────────────────────────────────
echo -e "  ${BOLD}Human Admin Account${NC}"
echo ""
echo -e "  ClawAV locks down the agent's user account (UID $WATCH_UID) so it"
echo -e "  cannot disable, modify, or bypass the watchdog."
echo ""
echo -e "  ${RED}${BOLD}⚠️  A separate human admin account is REQUIRED.${NC}"
echo -e "  ${YELLOW}This is the only account that can manage ClawAV after lockdown.${NC}"
echo -e "  ${YELLOW}Without it, you'll need recovery mode (boot from USB) to make changes.${NC}"
echo ""
echo -e "  ${RED}${BOLD}🔒 NEVER share this account's password with your AI agent.${NC}"
echo -e "  ${RED}${BOLD}   The entire security model depends on this separation.${NC}"
echo -e "  ${RED}${BOLD}   If the agent knows these credentials, it can bypass all protections.${NC}"
echo ""

AGENT_USERNAME=$(getent passwd "$WATCH_UID" | cut -d: -f1 || echo "")
ADMIN_USERNAME=""

# Check for existing admin accounts (sudo/admin group members that aren't the agent or root)
EXISTING_ADMINS=()
while IFS= read -r user; do
    [[ "$user" == "$AGENT_USERNAME" ]] && continue
    [[ "$user" == "root" ]] && continue
    EXISTING_ADMINS+=("$user")
done < <(getent group sudo 2>/dev/null | cut -d: -f4 | tr ',' '\n'; getent group admin 2>/dev/null | cut -d: -f4 | tr ',' '\n')
# Also check for clawav-created admin sudoers files
for f in /etc/sudoers.d/*; do
    [[ -f "$f" ]] || continue
    if grep -q "ClawAV.*Human admin" "$f" 2>/dev/null; then
        admin_from_file=$(grep -oP '^\w+' "$f" | head -1)
        [[ -n "$admin_from_file" && "$admin_from_file" != "$AGENT_USERNAME" ]] && EXISTING_ADMINS+=("$admin_from_file")
    fi
done
# Deduplicate
EXISTING_ADMINS=($(printf '%s\n' "${EXISTING_ADMINS[@]}" | sort -u))

if [[ ${#EXISTING_ADMINS[@]} -gt 0 ]]; then
    echo -e "  ${GREEN}✓ Found existing admin account(s): ${BOLD}${EXISTING_ADMINS[*]}${NC}"
    echo ""
    echo -en "  ${CYAN}Use existing admin account(s)? [Y/n]: ${NC}" > /dev/tty
    read -r use_existing < /dev/tty
    if [[ ! "$use_existing" =~ ^[nN] ]]; then
        log "Using existing admin account(s): ${EXISTING_ADMINS[*]}"
        ADMIN_USERNAME="${EXISTING_ADMINS[0]}"
        create_admin="n"
    else
        echo -en "  ${CYAN}Create an additional admin account? [Y/n]: ${NC}" > /dev/tty
        read -r create_admin < /dev/tty
    fi
else
    echo -en "  ${CYAN}Create a human admin account? [Y/n]: ${NC}" > /dev/tty
    read -r create_admin < /dev/tty
fi

if [[ "$create_admin" =~ ^[nN] && ${#EXISTING_ADMINS[@]} -eq 0 ]]; then
    echo ""
    warn "No admin account found and none being created."
    echo -en "  ${CYAN}Do you already have a separate admin account? [y/N]: ${NC}" > /dev/tty
    read -r has_admin < /dev/tty
    if [[ ! "$has_admin" =~ ^[yY] ]]; then
        die "Cannot proceed without a human admin account. Re-run the installer and create one."
    fi
fi

if [[ ! "$create_admin" =~ ^[nN] ]]; then
    echo -en "  ${CYAN}Username for admin account: ${NC}" > /dev/tty
    read -r ADMIN_USERNAME < /dev/tty
    [[ -n "$ADMIN_USERNAME" ]] || { warn "No username provided — skipping admin account"; ADMIN_USERNAME=""; }

    if [[ -n "$ADMIN_USERNAME" ]]; then
        if id "$ADMIN_USERNAME" &>/dev/null; then
            log "User '$ADMIN_USERNAME' already exists — adding to sudo group"
            usermod -aG sudo "$ADMIN_USERNAME" 2>/dev/null || true
        else
            log "Creating user '$ADMIN_USERNAME'..."
            useradd -m -s /bin/bash -G sudo "$ADMIN_USERNAME"
        fi

        # Set password
        echo ""
        echo -e "  ${BOLD}Set a password for '${ADMIN_USERNAME}':${NC}" > /dev/tty
        passwd "$ADMIN_USERNAME" < /dev/tty

        # Give full NOPASSWD sudo
        cat > "/etc/sudoers.d/$ADMIN_USERNAME" << SUDOEOF
# ClawAV: Human admin account — full unrestricted sudo access
$ADMIN_USERNAME ALL=(ALL:ALL) NOPASSWD: ALL
SUDOEOF
        chmod 440 "/etc/sudoers.d/$ADMIN_USERNAME"

        # Copy SSH authorized_keys from agent user if they exist
        if [[ -n "$AGENT_USERNAME" && -f "/home/$AGENT_USERNAME/.ssh/authorized_keys" ]]; then
            mkdir -p "/home/$ADMIN_USERNAME/.ssh"
            cp "/home/$AGENT_USERNAME/.ssh/authorized_keys" "/home/$ADMIN_USERNAME/.ssh/authorized_keys"
            chown -R "$ADMIN_USERNAME:$ADMIN_USERNAME" "/home/$ADMIN_USERNAME/.ssh"
            chmod 700 "/home/$ADMIN_USERNAME/.ssh"
            chmod 600 "/home/$ADMIN_USERNAME/.ssh/authorized_keys"
            log "Copied SSH keys from $AGENT_USERNAME → $ADMIN_USERNAME"
        fi

        echo ""
        log "✓ Admin account '$ADMIN_USERNAME' created with full sudo access"
        echo ""
        echo -e "  ${GREEN}Use this account for all system administration.${NC}"
        echo -e "  ${GREEN}SSH in as: ssh ${ADMIN_USERNAME}@$(hostname)${NC}"
        echo ""
        echo -e "  ${RED}${BOLD}╔════════════════════════════════════════════════════════════╗${NC}"
        echo -e "  ${RED}${BOLD}║  🚨  NEVER share '${ADMIN_USERNAME}' credentials with your AI agent  ║${NC}"
        echo -e "  ${RED}${BOLD}║  The agent CANNOT know this password or SSH key.          ║${NC}"
        echo -e "  ${RED}${BOLD}║  This is the foundation of ClawAV's security model.       ║${NC}"
        echo -e "  ${RED}${BOLD}╚════════════════════════════════════════════════════════════╝${NC}"
        echo ""
    fi
fi

# ── Install sudoers allowlist for agent ────────────────────────────────────────
if [[ -n "$AGENT_USERNAME" ]]; then
    install_sudoers_allowlist "$AGENT_USERNAME"
fi

# ── Install auditd tamper detection rules ─────────────────────────────────────
if command -v auditctl &>/dev/null; then
    log "Installing auditd tamper detection rules..."
    cat > /etc/audit/rules.d/clawav.rules << 'AUDITRULES'
# ClawAV tamper detection rules
-w /usr/local/bin/clawav -p a -k clawav-tamper
-w /etc/clawav/ -p wa -k clawav-config
-w /etc/systemd/system/clawav.service -p wa -k clawav-tamper
-w /etc/sudoers.d/clawav-deny -p wa -k clawav-tamper
-w /etc/apparmor.d/clawav.deny-agent -p wa -k clawav-tamper
AUDITRULES
    if auditctl -s 2>/dev/null | grep -q "enabled 2"; then
        log "ℹ️  Auditd in immutable mode — rules installed, will activate after reboot"
    else
        augenrules --load 2>/dev/null || auditctl -R /etc/audit/rules.d/clawav.rules 2>/dev/null || true
        log "✓ Auditd tamper detection active"
    fi
fi

# ── Create system user ────────────────────────────────────────────────────────
if ! id -u clawav &>/dev/null; then
    log "Creating clawav system user..."
    useradd --system --no-create-home --shell /usr/sbin/nologin clawav
fi
chown -R clawav:clawav /etc/clawav /var/log/clawav /var/run/clawav

# ── Set immutable attributes ─────────────────────────────────────────────────
log "Setting immutable flags (chattr +i)..."
chattr +i /usr/local/bin/clawav
chattr +i /usr/local/bin/clawsudo
chattr +i /etc/clawav/config.toml
chattr +i /etc/systemd/system/clawav.service
[[ -f /usr/local/bin/clawav-tray ]] && chattr +i /usr/local/bin/clawav-tray
[[ -f /etc/clawav/admin.key.hash ]] && chattr +i /etc/clawav/admin.key.hash
[[ -f /etc/sudoers.d/clawav-deny ]] && chattr +i /etc/sudoers.d/clawav-deny

# ── AppArmor profile ─────────────────────────────────────────────────────────
if command -v apparmor_parser &>/dev/null; then
    log "Installing AppArmor profile..."
    cat > /etc/apparmor.d/clawav.deny-agent <<'APPARMOR'
# Deny AI agent user access to ClawAV paths
/usr/local/bin/clawav r,
/usr/local/bin/clawsudo r,
deny /etc/clawav/** w,
deny /var/log/clawav/** w,
deny /etc/systemd/system/clawav.service w,
APPARMOR
    apparmor_parser -r /etc/apparmor.d/clawav.deny-agent 2>/dev/null || warn "AppArmor profile load failed (non-fatal)"
fi

# ── Kernel hardening ─────────────────────────────────────────────────────────
log "Applying kernel hardening..."
sysctl -w kernel.modules_disabled=1 2>/dev/null || warn "Could not disable module loading"
sysctl -w kernel.yama.ptrace_scope=2 2>/dev/null || warn "Could not set ptrace scope"

# ── Lock audit config ────────────────────────────────────────────────────────
if command -v auditctl &>/dev/null; then
    log "Locking audit configuration..."
    auditctl -e 2 2>/dev/null || warn "Could not lock auditd (may need reboot)"
fi

# ── Start the service ────────────────────────────────────────────────────────
log "Starting ClawAV..."
systemctl start clawav
sleep 2

if systemctl is-active --quiet clawav; then
    log "✓ ClawAV is running"
else
    warn "ClawAV did not start — check: journalctl -u clawav -n 50"
fi

# ═══════════════════════════════════════════════════════════════════════════════
# PHASE 4: ADMIN KEY
# ═══════════════════════════════════════════════════════════════════════════════
if [[ "$HAD_ADMIN_KEY" == "true" ]]; then
    echo ""
    echo -e "  ${GREEN}✓ Your existing admin key is still valid. No new key was generated.${NC}"
    echo ""
else
    echo ""
    echo ""
    echo -e "${RED}${BOLD}╔══════════════════════════════════════════════════════════════════╗${NC}"
    echo -e "${RED}${BOLD}║                                                                  ║${NC}"
    echo -e "${RED}${BOLD}║   ⚠️  SAVE YOUR ADMIN KEY — YOU WILL NOT SEE IT AGAIN ⚠️          ║${NC}"
    echo -e "${RED}${BOLD}║                                                                  ║${NC}"
    echo -e "${RED}${BOLD}║   Your admin key was displayed when ClawAV first started.        ║${NC}"
    echo -e "${RED}${BOLD}║   Check the service logs:                                        ║${NC}"
    echo -e "${RED}${BOLD}║                                                                  ║${NC}"
    echo -e "${RED}${BOLD}║     sudo journalctl -u clawav -n 50 | grep OCAV-                 ║${NC}"
    echo -e "${RED}${BOLD}║                                                                  ║${NC}"
    echo -e "${RED}${BOLD}║   WITHOUT THIS KEY:                                              ║${NC}"
    echo -e "${RED}${BOLD}║   • You cannot pause, configure, or manage ClawAV                ║${NC}"
    echo -e "${RED}${BOLD}║   • You cannot update or uninstall it                            ║${NC}"
    echo -e "${RED}${BOLD}║   • Your ONLY option is RECOVERY MODE (boot from USB)            ║${NC}"
    echo -e "${RED}${BOLD}║                                                                  ║${NC}"
    echo -e "${RED}${BOLD}║   Save it in your password manager NOW.                          ║${NC}"
    echo -e "${RED}${BOLD}║                                                                  ║${NC}"
    echo -e "${RED}${BOLD}╚══════════════════════════════════════════════════════════════════╝${NC}"
    echo ""
    echo ""

    # Show the key right here if we can find it
    ADMIN_KEY=$(journalctl -u clawav -n 50 --no-pager 2>/dev/null | grep -oP 'OCAV-[a-f0-9]+' | head -1)
    if [[ -n "$ADMIN_KEY" ]]; then
        echo -e "  ${BOLD}Your admin key:${NC}"
        echo ""
        echo -e "    ${GREEN}${BOLD}$ADMIN_KEY${NC}"
        echo ""
    fi

    while true; do
        echo -en "${RED}${BOLD}  Type 'I SAVED MY KEY' to confirm: ${NC}" > /dev/tty
        read -r response < /dev/tty
        if [[ "$response" == "I SAVED MY KEY" ]]; then
            break
        fi
        echo -e "  ${RED}You must type exactly: I SAVED MY KEY${NC}" > /dev/tty
    done
fi

echo ""
echo -e "${GREEN}${BOLD}═══════════════════════════════════════════════════════════════${NC}"
echo -e "${GREEN}${BOLD}  ✅  ClawAV $VERSION installed and locked down                ${NC}"
echo -e "${GREEN}${BOLD}═══════════════════════════════════════════════════════════════${NC}"
echo ""
echo -e "  ${BOLD}Binaries:${NC}  /usr/local/bin/clawav, /usr/local/bin/clawsudo"
echo -e "  ${BOLD}Config:${NC}    /etc/clawav/config.toml (immutable)"
echo -e "  ${BOLD}Logs:${NC}      journalctl -u clawav -f"
echo -e "  ${BOLD}Status:${NC}    systemctl status clawav"
echo -e "  ${BOLD}Patterns:${NC}  /etc/clawav/secureclaw/"
echo ""
