#!/bin/bash
# Setup auditd rules to monitor the openclaw user
# Run as root

set -euo pipefail

WATCHED_USER="${CLAWTOWER_WATCHED_USER:-${OPENCLAW_USER:-openclaw}}"
WATCHED_UID=$(id -u "$WATCHED_USER" 2>/dev/null || echo "")
WATCHED_HOME=$(getent passwd "$WATCHED_USER" 2>/dev/null | cut -d: -f6)

if [ -z "$WATCHED_HOME" ]; then
    WATCHED_HOME="/home/$WATCHED_USER"
fi

if [ -z "$WATCHED_UID" ]; then
    echo "ERROR: User '$WATCHED_USER' not found"
    exit 1
fi

# Detect architecture for correct syscall names
ARCH=$(uname -m)
echo "Detected architecture: $ARCH"

case "$ARCH" in
    x86_64)
        PERM_SYSCALLS="chmod,fchmod,chown,fchown"
        ;;
    aarch64)
        # ARM64 doesn't have chmod/chown syscalls; uses fchmodat/fchownat instead
        PERM_SYSCALLS="fchmodat,fchmod,fchownat,fchown"
        ;;
    *)
        echo "WARNING: Unknown architecture '$ARCH', falling back to fchmodat/fchownat (portable)"
        PERM_SYSCALLS="fchmodat,fchmod,fchownat,fchown"
        ;;
esac

echo "Setting up auditd rules for user $WATCHED_USER (uid=$WATCHED_UID)..."
echo "Using syscalls for file permission monitoring: $PERM_SYSCALLS"

# Install auditd if not present
if ! command -v auditctl &>/dev/null; then
    if command -v apt-get &>/dev/null; then
        apt-get update && apt-get install -y auditd
    elif command -v dnf &>/dev/null; then
        dnf install -y audit
    elif command -v yum &>/dev/null; then
        yum install -y audit
    else
        echo "ERROR: Could not find apt-get/dnf/yum to install auditd"
        exit 1
    fi
fi

# Build the -S flags for permission syscalls
PERM_S_FLAGS=""
IFS=',' read -ra SYSCALLS <<< "$PERM_SYSCALLS"
for sc in "${SYSCALLS[@]}"; do
    PERM_S_FLAGS="$PERM_S_FLAGS -S $sc"
done

# Write rules file
cat > /etc/audit/rules.d/clawtower.rules << EOF
# ClawTower — Monitor openclaw user activity
# Generated by setup-auditd.sh
# Architecture: $ARCH

# Monitor all process execution by openclaw
-a always,exit -F arch=b64 -S execve -F uid=$WATCHED_UID -k clawtower_exec

# Monitor file access to sensitive dirs
-w /etc/clawtower/ -p rwxa -k clawtower_tamper
-w /usr/local/bin/clawtower -p rwxa -k clawtower_tamper
-w /etc/systemd/system/clawtower.service -p rwxa -k clawtower_tamper

# Monitor privilege escalation attempts
-a always,exit -F arch=b64 -S setuid -S setgid -S setreuid -S setregid -F uid=$WATCHED_UID -k clawtower_privesc

# Monitor network socket creation
-a always,exit -F arch=b64 -S socket -S connect -F uid=$WATCHED_UID -k clawtower_net

# Monitor file permission changes (arch-specific syscalls)
-a always,exit -F arch=b64${PERM_S_FLAGS} -F uid=$WATCHED_UID -k clawtower_perm

# Monitor module loading attempts
-a always,exit -F arch=b64 -S init_module -S finit_module -k clawtower_module

# Monitor credential file reads (exfiltration / recon)
-w $WATCHED_HOME/.openclaw/agents/main/agent/auth-profiles.json -p r -k clawtower_cred_read
-w $WATCHED_HOME/.aws/credentials -p r -k clawtower_cred_read
-w $WATCHED_HOME/.aws/config -p r -k clawtower_cred_read
-w $WATCHED_HOME/.ssh/id_ed25519 -p r -k clawtower_cred_read
-w $WATCHED_HOME/.ssh/id_rsa -p r -k clawtower_cred_read
-w $WATCHED_HOME/.env -p r -k clawtower_cred_read
-w $WATCHED_HOME/.openclaw/gateway.yaml -p r -k clawtower_cred_read
EOF

# Reload rules
augenrules --load
echo "Auditd rules loaded. $(auditctl -l | grep -c clawtower) ClawTower rules active."
