# ClawTower Default Detection Policies
#
# Philosophy: Flag genuinely suspicious behavior, not normal operations.
# The agent (Claw/OpenClaw) runs commands via bash -c — that's normal.
# What's NOT normal: reverse shells, encoded payloads to unknown hosts,
# credential theft, security tool tampering, privilege escalation.

rules:
  # ── Data Exfiltration ──────────────────────────────────────────────────────
  - name: "block-data-exfiltration"
    description: "Flag curl/wget to unknown hosts (allowlist our services)"
    match:
      command: ["curl", "wget", "nc", "ncat", "netcat", "socat"]
      exclude_args:
        # Our services
        - "gottamolt.gg"
        - "mahamedia.us"
        - "localhost"
        - "127.0.0.1"
        # APIs we legitimately use
        - "api.anthropic.com"
        - "api.openai.com"
        - "github.com"
        - "raw.githubusercontent.com"
        - "api.brave.com"
        - "hooks.slack.com"
        # AWS: specific service endpoints only (not broad amazonaws.com)
        - "ssm.us-east-1.amazonaws.com"
        - "s3.us-east-1.amazonaws.com"
        - "ec2.us-east-1.amazonaws.com"
        - "sts.amazonaws.com"
        - "route53.amazonaws.com"
        - "cloudfront.amazonaws.com"
        - "169.254.169.254"
        # Loopback
        - "::1"
        # Package managers
        - "registry.npmjs.org"
        - "crates.io"
        - "pypi.org"
        # Utilities
        - "wttr.in"
        - "api.open-meteo.com"
        - "claw.local"
    action: critical

  # ── Reverse Shell Detection ────────────────────────────────────────────────
  - name: "detect-reverse-shell"
    description: "Detect reverse shell patterns"
    match:
      command_contains:
        - "/dev/tcp/"
        - "/dev/udp/"
        - "mkfifo"
        - "bash -i"
        - "sh -i"
        - "python -c 'import socket"
        - "python3 -c 'import socket"
        - "perl -e 'use Socket"
        - "ruby -rsocket"
        - "nc -e"
        - "ncat -e"
    action: critical

  # ── Encoded/Obfuscated Commands ────────────────────────────────────────────
  - name: "detect-encoded-commands"
    description: "Flag base64-encoded or heavily obfuscated command execution"
    match:
      command_contains:
        - "base64 -d |"
        - "base64 --decode |"
        - "| base64 -d"
        - "| base64 --decode"
        - "eval $(echo"
        - "echo -e '\\x"
        - "python -c 'exec("
        - "python3 -c 'exec("
    action: critical

  # ── Credential Theft ───────────────────────────────────────────────────────
  - name: "deny-shadow-read"
    description: "Alert on sensitive credential file access"
    match:
      file_access:
        - "/etc/shadow"
        - "/etc/gshadow"
        - "/etc/master.passwd"
        - "/etc/sudoers"
        - "/etc/sudoers.d/*"
    action: critical

  - name: "recon-sensitive-files"
    description: "Flag access to credential/secret files"
    match:
      file_access:
        - "**/.env"
        - "**/.aws/credentials"
        - "**/.aws/config"
        - "**/.ssh/id_rsa"
        - "**/.ssh/id_ed25519"
        - "**/.ssh/config"
        - "**/.gnupg/**"
        - "**/.kube/config"
    action: warning

  # ── System Tampering ───────────────────────────────────────────────────────
  - name: "deny-sensitive-write"
    description: "Alert on writes to critical system files"
    match:
      file_access:
        - "/etc/passwd"
        - "/etc/hosts"
        - "/etc/crontab"
        - "/etc/shadow"
    action: critical

  - name: "deny-firewall-changes"
    description: "Alert on firewall/security modifications"
    match:
      command_contains:
        - "ufw disable"
        - "iptables -F"
        - "iptables --flush"
        - "nft flush"
        - "setenforce 0"
        - "aa-teardown"
    action: critical

  - name: "deny-security-service-disable"
    description: "Alert on disabling security services"
    match:
      command_contains:
        - "systemctl stop clawtower"
        - "systemctl disable clawtower"
        - "systemctl stop apparmor"
        - "systemctl disable apparmor"
        - "systemctl stop auditd"
        - "systemctl disable auditd"
        - "systemctl stop fail2ban"
        - "systemctl disable fail2ban"
    action: critical

  # ── ClawTower Tamper Detection ────────────────────────────────────────────────
  - name: "deny-clawtower-tamper"
    description: "Detect attempts to modify ClawTower itself"
    match:
      command_contains:
        - "chattr -i"
        - "chattr -a"
        - "auditctl -D"
        - "auditctl -e 0"
        - "apparmor_parser -R"
        - "systemctl mask clawtower"
        - "rm /usr/local/bin/clawtower"
        - "rm /usr/local/bin/clawsudo"
        - "rm -rf /etc/clawtower"
    action: critical

  - name: "deny-clawtower-config-write"
    description: "Detect writes to ClawTower config files"
    match:
      command_contains:
        - "sed -i /etc/clawtower/"
        - "tee /etc/clawtower/"
        - "vim /etc/clawtower/"
        - "nano /etc/clawtower/"
        - "vi /etc/clawtower/"
        - "chattr -i /etc/clawtower/"
    action: critical

  # ── Privilege Escalation ───────────────────────────────────────────────────
  - name: "detect-priv-escalation"
    description: "Flag privilege escalation attempts"
    match:
      command_contains:
        - "chmod u+s"
        - "chmod 4755"
        - "chmod 4777"
        - "setcap cap_"
        - "visudo"
        - "usermod -aG sudo"
        - "usermod -aG wheel"
    action: critical

  # ── Crypto / Miners ────────────────────────────────────────────────────────
  - name: "detect-crypto-miner"
    description: "Flag potential cryptocurrency mining"
    match:
      command_contains:
        - "xmrig"
        - "minerd"
        - "cpuminer"
        - "stratum+tcp"
        - "nicehash"
        - "cryptonight"
    action: critical

  # ── Recon (informational only) ─────────────────────────────────────────────
  - name: "recon-network"
    description: "Flag network reconnaissance tools"
    match:
      command: ["nmap", "masscan", "nikto", "sqlmap", "dirb", "gobuster"]
    action: warning

  # ── Dangerous Destructive Commands ─────────────────────────────────────────
  - name: "deny-dangerous-rm"
    description: "Flag dangerous recursive deletions"
    match:
      command_contains:
        - "rm -rf /"
        - "rm -rf /etc"
        - "rm -rf /usr"
        - "rm -rf /var"
        - "rm -rf /home"
        - "rm -rf /boot"
        - "dd if=/dev/zero of=/dev"
        - "mkfs."
        - "> /dev/sda"
    action: critical

  # ── Encoding/Obfuscation Detection ─────────────────────────────────────────
  - name: "detect-encoding-obfuscation"
    description: "Flag use of encoding tools for potential data exfiltration"
    match:
      command_contains:
        - "xxd"
        - "od -x"
        - "hexdump"
        - "base64 | curl"
        - "base64 | wget"
        - "base32 | nc"
    action: warning

  # ── Suspicious File Extensions ─────────────────────────────────────────────
  - name: "detect-suspicious-temp-files"
    description: "Flag creation of suspicious binaries in temporary directories"
    match:
      file_access:
        - "/tmp/*.elf"
        - "/tmp/*.so"
        - "/tmp/*.bin"
        - "/tmp/*.exe"
        - "/var/tmp/*.elf"
        - "/var/tmp/*.so"
    action: warning

  # ── Large File Exfiltration ────────────────────────────────────────────────
  - name: "detect-large-file-exfil"
    description: "Flag compression/archiving of sensitive directories"
    match:
      command_contains:
        - "tar -czf"
        - "tar -cf"
        - "zip -r /etc"
        - "zip -r /var"
        - "zip -r /home"
        - "7z a /etc"
        - "7z a /var"
    action: warning

  # ── AWS Credential Theft ───────────────────────────────────────────────────
  - name: "detect-aws-credential-theft"
    description: "Flag AWS credential enumeration from unexpected contexts"
    match:
      command_contains:
        - "aws sts get-session-token"
        - "aws sts assume-role"
        - "aws configure get"
        - "aws configure list"
        - "cat ~/.aws/credentials"
        - "cat ~/.aws/config"
    action: warning

  # ── Git Credential Exposure ────────────────────────────────────────────────
  - name: "detect-git-credential-exposure"
    description: "Flag potential git credential theft"
    match:
      command_contains:
        - "git config credential"
        - "git config user.token"
        - "git config --global credential"
        - "cat .git/config"
        - "cat ~/.gitconfig"
    action: warning

  # ── Crontab Modification ───────────────────────────────────────────────────
  - name: "detect-crontab-modification"
    description: "Flag modifications to cron scheduling"
    match:
      command_contains:
        - "crontab -e"
        - "crontab -r"
      file_access:
        - "/etc/cron.d/*"
        - "/etc/cron.daily/*"
        - "/etc/cron.hourly/*"
        - "/etc/cron.weekly/*"
        - "/etc/cron.monthly/*"
        - "/etc/crontab"
        - "/var/spool/cron/*"
    action: critical

  # ── SSH Key Injection ──────────────────────────────────────────────────────
  - name: "detect-ssh-key-injection"
    description: "Flag attempts to inject SSH keys for persistence"
    match:
      file_access:
        - "**/.ssh/authorized_keys"
        - "/root/.ssh/authorized_keys"
    action: critical

  # ── History Tampering ──────────────────────────────────────────────────────
  - name: "detect-history-tampering"
    description: "Flag attempts to clear or modify command history"
    match:
      command_contains:
        - "rm .bash_history"
        - "rm .zsh_history"
        - "> .bash_history"
        - "> .zsh_history"
        - "unset HISTFILE"
        - "HISTSIZE=0"
        - "HISTFILESIZE=0"
      file_access:
        - "**/.bash_history"
        - "**/.zsh_history"
    action: critical

  # ── Process Injection ──────────────────────────────────────────────────────
  - name: "detect-process-injection"
    description: "Flag ptrace and memory manipulation for process injection"
    match:
      command_contains:
        - "ptrace"
        - "gdb attach"
        - "gdb -p"
        - "/proc/*/mem"
        - "PTRACE_ATTACH"
        - "strace -p"
    action: critical

  # ── Timestomping ───────────────────────────────────────────────────────────
  - name: "detect-timestomping"
    description: "Flag attempts to modify file timestamps"
    match:
      command_contains:
        - "touch -t"
        - "touch --date"
        - "touch -d"
        - "touch -r"
    action: warning

  # ── Log Clearing ───────────────────────────────────────────────────────────
  - name: "detect-log-clearing"
    description: "Flag attempts to clear system logs"
    match:
      command_contains:
        - "> /var/log/syslog"
        - "> /var/log/auth.log"
        - "> /var/log/audit/audit.log"
        - "rm /var/log/"
        - "truncate /var/log/"
        - "journalctl --vacuum"
        - "journalctl --rotate"
    action: critical

  # ── Binary Replacement ─────────────────────────────────────────────────────
  - name: "detect-binary-replacement"
    description: "Flag overwriting of system binaries"
    match:
      command_contains:
        - "cp * /usr/bin/"
        - "cp * /usr/sbin/"
        - "cp * /bin/"
        - "cp * /sbin/"
        - "mv * /usr/bin/"
        - "mv * /usr/sbin/"
        - "mv * /bin/"
        - "mv * /sbin/"
        - "install * /usr/bin/"
        - "install * /usr/sbin/"
        - "install * /bin/"
        - "install * /sbin/"
    action: critical

  # ── Kernel Parameter Changes ───────────────────────────────────────────────
  - name: "detect-kernel-param-changes"
    description: "Flag runtime kernel parameter modifications"
    match:
      command_contains:
        - "sysctl -w"
        - "echo > /proc/sys/"
      file_access:
        - "/proc/sys/kernel/*"
        - "/proc/sys/net/*"
    action: warning

  # ── Service Creation ───────────────────────────────────────────────────────
  - name: "detect-service-creation"
    description: "Flag creation of new system services"
    match:
      command_contains:
        - "systemctl enable"
        - "update-rc.d"
        - "chkconfig"
      file_access:
        - "/etc/systemd/system/*"
        - "/usr/lib/systemd/system/*"
        - "/etc/init.d/*"
    action: warning

  # ── Network Tunnel Creation ────────────────────────────────────────────────
  - name: "detect-network-tunnels"
    description: "Flag creation of network tunnels for C2"
    match:
      command_contains:
        - "ssh -R"
        - "ssh -L"
        - "ssh -D"
        - "chisel"
        - "ngrok"
        - "socat"
        - "proxytunnel"
        - "stunnel"
    action: critical

  # ── Package Manager Abuse ──────────────────────────────────────────────────
  - name: "detect-package-manager-abuse"
    description: "Flag suspicious package installations"
    match:
      command_contains:
        - "pip install git+"
        - "pip install http://"
        - "npm install git+"
        - "npm install http://"
        - "gem install --source http://"
        - "go get"
        - "cargo install --git"
    action: warning

  # ── Compiler Invocation ───────────────────────────────────────────────────
  - name: "detect-compilation"
    description: "Flag compilation activity (potential exploit building)"
    match:
      command: ["gcc", "g++", "clang", "cc", "make", "cmake", "rustc"]
      command_contains:
        - "gcc"
        - "g++"
        - "clang"
        - "make"
        - "go build"
    action: info

  # ── Memory Dump Tools ──────────────────────────────────────────────────────
  - name: "detect-memory-dump"
    description: "Flag memory dumping and analysis tools"
    match:
      command_contains:
        - "gdb attach"
        - "/proc/kcore"
        - "dd if=/proc/kcore"
        - "volatility"
        - "memdump"
        - "lldb -p"
    action: critical

  # ── Scheduled Task Manipulation ────────────────────────────────────────────
  - name: "detect-scheduled-tasks"
    description: "Flag manipulation of scheduled tasks"
    match:
      command: ["at", "atq", "atrm", "batch"]
    action: warning
